#Repository properties
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mutants?useSSL=false
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

#Applictaion messages
app:
  exception:
    ioexception:
      message: "Error durante el proceso de validación de ADN"
